Repository praveenscience/easya-website, pull requests merged in 2021-05, with the labels that each got.

#25 Added Custom Scrollbar
  src/assets/downarrow.png
  src/assets/uparrow.png
  src/styles/App.scss
Labels: GSSoC21, Level0, enhancement

#26 Removed links to the Mobile Apps.
  src/components/Shared/Footer/_About.js
Labels: GSSoC21, Level0, enhancement

#36 Added hover effect for Navbar
  src/styles/Shared/Header/_PrimaryNav.scss
Labels: GSSoC21, Level0

#32 Added Scroll Top feature in each page of website
  package-lock.json
  package.json
  public/index.html
  src/components/ATBT/ATBT.js
  src/components/About/About.js
  src/components/Blog/Blog.js
  src/components/BlogDetails/BlogDetails.js
  src/components/ContactUs/ContactUs.js
  src/components/FAQs/FAQs.js
  src/components/Home/Home.js
  src/components/Home/_scrolltop.js
  src/components/HowItWorks/HowItWorks.js
  src/components/InfoPages/Privacy.js
  src/components/InfoPages/Terms.js
  src/components/Pricing/MonthlyPricing.js
  src/components/Pricing/Pricing.js
  src/components/Subjects/Subjects.js
  src/components/TeachingMethods/TeachingMethods.js
  src/components/Testimonials/Testimonials.js
  src/components/WMCAL/WMCAL.js
  src/styles/Home/_scrolltop.scss
Labels: GSSoC21, Level1, enhancement

#39 Resetting and styling for more vibrant look
  package-lock.json
  package.json
  src/styles/About/_AboutBrains.scss
  src/styles/About/_AboutCurious.scss
  src/styles/About/_AboutFeatTutors.scss
  src/styles/About/_AboutGPS.scss
  src/styles/About/_AboutIntro.scss
  src/styles/About/_AboutLearn.scss
  src/styles/About/_AboutTeam.scss
  src/styles/Blog/Blog.scss
  src/styles/Blog/_BlogFeatured.scss
  src/styles/Blog/_BlogIntro.scss
  src/styles/Blog/_BlogList.scss
  src/styles/Blog/_BlogPost.scss
  src/styles/Blog/_BlogRecentList.scss
  src/styles/BlogDetails/_BDBanner.scss
  src/styles/ContactUs/_ContactFAQ.scss
  src/styles/ContactUs/_ContactHelp.scss
  src/styles/ContactUs/_ContactIntro.scss
  src/styles/ContactUs/_ContactQuestions.scss
  src/styles/FAQs/_FAQsHelp.scss
  src/styles/FAQs/_FAQsIntro.scss
  src/styles/FAQs/_FAQsList.scss
  src/styles/Home/_BackedByBanner.scss
  src/styles/Home/_Child247.scss
  src/styles/Home/_HomeBanner.scss
  src/styles/Home/_HomeParentTestimonial.scss
  src/styles/Home/_HomePlans.scss
  src/styles/Home/_HomeSubjects.scss
  src/styles/HowItWorks/_HIWIntro.scss
  src/styles/HowItWorks/_HIWStep.scss
  src/styles/Pricing/_MonthlyPricingIntro.scss
  src/styles/Pricing/_PricingFAQ.scss
  src/styles/Pricing/_PricingIntro.scss
  src/styles/Pricing/_PricingMoreReasons.scss
  src/styles/Pricing/_PricingTrusted.scss
  src/styles/Subjects/_SubjectBlock.scss
  src/styles/Subjects/_SubjectCurious.scss
  src/styles/Subjects/_SubjectsHomeParentTestimonial.scss
  src/styles/Subjects/_SubjectsIntro.scss
  src/styles/TeachingMethods/TeachingMethods.scss
  src/styles/Testimonials/_TestIntro.scss
  src/styles/Testimonials/_TestReviews.scss
  src/styles/WMCAL/WMCAL.scss
  src/styles/WMCAL/_WMCALApproach.scss
  src/styles/WMCAL/_WMCALBlogs.scss
  src/styles/WMCAL/_WMCALBoard.scss
  src/styles/WMCAL/_WMCALIntro.scss
  src/styles/WMCAL/_WMCALPrinciples.scss
  src/styles/WMCAL/_WMCALReviews.scss
  src/styles/_Overrides.scss
Labels: GSSoC21, Level0, design

#35 Added How it works text to button
  src/components/Home/_Child247.js
Labels: GSSoC21, Level0

#42 Need new logos for this website! #27
  public/logo.png
Labels: GSSoC21, Level0, design
